all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
  vars:
    app_name: flask-devops-pipeline
    app_port: 5000
    docker_compose_file: docker/docker-compose.yml
